### ISSUE TITLE
AttributError in fields.py for Function

### ISSUE THREAD

**Issue by Barneby77** [pydicom/deid#298]
Hi Deid - Team!

When updating from deid 0.4.6 to 0.4.7 I get this error in the log:
```
 python3.11/site-packages/deid/dicom/fields.py", line 376, in _get_field_lookup_keys case_insensitive_field = field.lower()
AttributeError : 
'function' object has no attribute 'lower'
```
For debugging I added the line with the prints to the code of _get_field_lookup_keys:

```
    def _get_field_lookup_keys(self, field):
        if not isinstance(field, DicomField):
            print(field, type(field))
            case_insensitive_field = field.lower()
```

With the next run I get this right before the traceback:

```
<function shiftDate at 0x7f1ed292bb00>
<class 'function'>
```

shiftDate is a function that I created and use in the recipe as follows:

REPLACE StudyDate func:shiftDate

Are functions no longer supported?

**Comment by vsoch** [comment]
@Barneby77 functions should work. This was likely a bug introduced somewhere around https://github.com/pydicom/deid/pull/289. Could you try the latest version of pypi, and if the bug is still there, I'll ping the contributor?

**Comment by Barneby77** [comment]
I tested the package upgrade in a new venv. So everything should be up to date. Just checked again:
```
pip == 25.3
pydicom == 3.0.1
```
Seems the lower() works for strings, but not for the passed function.

**Comment by Barneby77** [comment]
Hi Deid-Team,
we have been testing a bit more with Deid version 0.4.6 and there seems to be an issue concerning functions already.

For one of our other funtions (generate_uid) I get this message in the log:
`WARNING generate_uid  not found in item lookup`

The warning message is generated in [deid/utils/actions.py]

With some prints I found out that:
- the function is correctly listed in the dictionary item.
- the problem is in the variable value_option. Instead of "generate_uid" it prints "generate_uid " with a trailing blank.

The trailing blank is also visible in the warning message: between "generate_uid" and "not" there are two blanks :-/

So the code must fail:
```
if value_option not in item:
  bot.warning("%s not found in item lookup." % (value_option))
  return None
```

Edit: Ahh, seems there was a blank at the end of the line in the recipe plus a commt beginning with '#'. Deleting this solved it :))

**Comment by vsoch** [comment]
Can you please provide a reproducing case? E.g., a dummy example of exactly what you are running and seeing so I can suggest a change.

**Comment by Barneby77** [comment]
Sure :-)
Whenever I put a comment at the end of the line in the recipe after a function, I get this error. An example entry in the recipe would be:

`REPLACE StudyDate func:shiftDate # Any comment`

This leads then to the line in the console:

`WARNING shiftDate  not found in item lookup.`

Maybe a rstrip() for the variable value_option would solve the issue :-)
In this case it prints "shiftDate "

**Comment by vsoch** [comment]
You are adding your function to the extracted items dictionary? The error is explicitly telling you it cannot find it.

**Comment by Barneby77** [comment]
No. A college added a comment at the end of the line in the recipe for one of our custom functions. An example would be:
`REPLACE StudyDate func:shiftDate # Any comment`
This directly leads to the error:
`WARNING shiftDate  not found in item lookup.`

When debugging I found out,
- the function is correctly added to the dictionary item
- the variable value options prints "shiftDate " with a trailing blank
- that's why the condition `if value_option not in item` is true
- If you look carefully, you already see this in the log message. There are two blanks between shiftDate and not.

The question is whether you consider this a bug. In case you want to allow comments at the end of a line in the recipe for functions, which is valid Python, the rstrip() for value_option could be a solution (to get rid of the trailing blank). But I didn't try it.
What I also did not try it to add a comment at the end of any other entry in the recipe.

The problem for us was, that the function was not executed and it took us some time to find the warning message hidden in the console. 
The incomplete execution of the recipe is a problem. Instead of a warning, this should be treated as an error or, even cause the process to be terminated.

**Comment by vsoch** [comment]
We likely can support a cleanup of comments. The issue could arise if there is some function input with that character that is _not_ a comment, then we have a bug in the other direction. Can you think of such cases? I'm happy to review a pull requests that addresses this issue. Thank you @Barneby77 !
